### ISSUE TITLE
Project rebar.config file

### ISSUE THREAD

**Issue by JrIndie** [inaka/worker_pool#124]
Hello, new to rebar, and was wondering what I would use for this?

{deps, [
    {?, "?", {git, "https://github.com/inaka/worker_pool", {tag, "?"}}}
]}.

Thank you ...

**Comment by elbrujohalcon** [comment]
Check the instructions on https://hex.pm/packages/worker_pool

**Comment by elbrujohalcon** [comment]
We should probably add that to the readme...

**Comment by JrIndie** [comment]
{worker_pool, "3.0.0", {git, "https://github.com/inaka/worker_pool", {tag, "3.0.0"}}} - case anyone else needs it.

**Comment by elbrujohalcon** [comment]
@JrIndie or, as I stated above, much better to use
```
{worker_pool, "~> 3.0"}
```
or similar, from hex.pm
