### ISSUE TITLE
wpool:broadcast issue

### ISSUE THREAD

**Issue by JrIndie** [inaka/worker_pool#126]
Very sorry to post so many questions :) -- I use wpool:start_sup_pool, and I want to broadcast a command for all workers to work, however while calling: wpool:broadcast, I get the following error:

Im thinking broadcast is not defined:
{undef,[{wpool,broadcast, ...

wpool:call, and wpool:cast work!

**Comment by elbrujohalcon** [comment]
You're probably not using the latest version of wpool ;) - can you confirm you're using 3.0.0?

**Comment by JrIndie** [comment]
Yes: https://github.com/inaka/worker_pool/issues/124#issuecomment-322453438

Also: worker_pool/ebin/worker_pool.app -> {vsn,"3.0.0"},

**Comment by elbrujohalcon** [comment]
OK, then… can you paste the whole error here, please?

**Comment by JrIndie** [comment]
I just tested and made sure both of these work:

wpool:call(listen_worker, {test})
wpool:cast(listen_worker, {test})
(output)
listen_worker:handle_call {test} -> PID[<0.121.0>]
listen_worker:handle_cast {test} -> PID[<0.121.0>]


wpool:broadcast(listen_worker, {test})
(output)
{undef,[{wpool,broadcast,[listen_worker,{test}],[]},
        {listen,init,0,[{file,"listen.erl"},{line,28}]},
        {chat_app,init,0,[{file,"chat_app.erl"},{line,23}]}]}

**Comment by JrIndie** [comment]
If it helps, I am using IntelliJ, with https://github.com/ignatov/intellij-erlang on Windows 10 64bit, and there were some hickups on windows environment (have to set my own flags):

-pa D:\Erlang-Workspace\Chat\deps\worker_pool\ebin

Maybe this is related to this somehow?

**Comment by JrIndie** [comment]
Its not in 3.0.0!  https://github.com/inaka/worker_pool/blob/3.0.0/src/wpool.erl 👍

**Comment by elbrujohalcon** [comment]
So, it's not released yet! @Euen any plans for releasing a new version of wpool soon?

**Comment by elbrujohalcon** [comment]
@harenson maybe?

**Comment by JrIndie** [comment]
In the meantime, is there anyway I can hack it to cast for each worker?

**Comment by Euen** [comment]
You already can find the release in hex.pm https://hex.pm/packages/worker_pool/3.1.0 @JrIndie @elbrujohalcon 👍
