### ISSUE TITLE
wpool:stop_sup_pool() can't fire gen_server terminate

### ISSUE THREAD

**Issue by boboxiaodd** [inaka/worker_pool#132]
i want do something when the worker gen_server terminate,
but not fire !

wpool_process_sup.erl
use {one_for_one, 5, 60}

wpool_sup.erl
use {simple_one_for_one, 5, 60}

maybe wpool_sup use simple_one_for_one ,and can't fire terminate each process,
and wpool_process_sup also can't fire terminate

**Comment by elbrujohalcon** [comment]
Sorry @boboxiaodd, it's really hard to understand what you want. Can you show us some examples of your code with expected results and actual results so that we can reproduce your issue and help you with it?
Thanks :)

**Comment by boboxiaodd** [comment]
Application
```erlang
-module(push_app).
-behaviour(application).
-export([start/2, stop/1,prep_stop/1]).
-define(POOL_NAME,push_pool).

start(_StartType , _StartArgs) ->
	error_proc:register_logger({node()}),
    jky_util:ensure_app_started(worker_pool),
    wpool:start_sup_pool(
        ?POOL_NAME,
        [
            {overrun_warning,5000},
            {workers, 5},
            {work_type, gen_server},
            {worker, {push_work_pool, []}}
        ]
    ).


stop(_) ->
    error_logger:info_msg("push_app application stop...~n"), %%work
    ok.

prep_stop(_) ->
    wpool:stop_sup_pool(?POOL_NAME),
    error_logger:info_msg("application prep_stop..."),  %%work
    ok.
```

Worker:  push_work_pool.erl
```erlang
terminate(Reason, _State) ->
	error_logger:info_msg("Push server [~p] shutdown...~p~n", [self(), Reason]), %%Don't Work
	ok.
```

**Comment by elbrujohalcon** [comment]
I see… I believe you can fix your problem by adding `{pool_sup_shutdown, 5000}` to the list of options when you start the queue (and by the way: it's `worker_type` not `work_type`).
I didn't test it yet, tho. I'll run some tests later and let you know.

**Comment by boboxiaodd** [comment]
i added {pool_sup_shutdown, 5000} ,it  dont't work .
maybe we must change  simple_one_for_one to one_for_one in wpool_sup.erl

**Comment by elbrujohalcon** [comment]
@boboxiaodd yeah… the problem is not related (or only partially related) to the shutdown strategy of the supervisor.
The problem is related to the internal logic of gen_server callbacks.
If you read [the docs](http://erlang.org/doc/man/gen_server.html#Module:terminate-2) you'll see that…
> If the `gen_server` process is part of a supervision tree and is ordered by its supervisor to terminate, this function is called with `Reason=shutdown` if the following conditions apply:
> * The `gen_server` process has been set to trap exit signals.
> * The shutdown strategy as defined in the child specification of the supervisor is an integer time-out value, not `brutal_kill`.

So, on one hand, you should totally set `{pool_sup_shutdown, …}` to something other than `brutal_kill`, but you also need to add `process_flag(trap_exit, true)` to your `push_work_pool` code. I would recommend you to add it to `init/1`.

**Comment by boboxiaodd** [comment]
@elbrujohalcon Thank you! It work!
