### ISSUE TITLE
get_pending_tasks Function

### ISSUE THREAD

**Issue by ferigis** [inaka/worker_pool#135]
Create a function which retrieves the pending tasks for a pool, in order to know if we are overloading it or not.
i.e. For `available_worker` strategy we would return 
```erlang
get(pending_tasks)
```

**Comment by elbrujohalcon** [comment]
I would recommend returning the # of pending tasks, and not the pending tasks themselves.
I would also recommend just adding the info to `wpool:stats/0,1`.

**Comment by ferigis** [comment]
yeah! that was what I wanted to mean :trollface:

**Comment by ferigis** [comment]
closing, this function is not needed
