### ISSUE TITLE
Propagate `killed` reason to clients

### ISSUE THREAD

**Issue by carlosvarelap** [inaka/worker_pool#140]
When a worker is killed by some reason (as when then maximum heap size is reached), the client is not receiving any information about it but a timeout. I was expecting to receive an exit(killed) as with exit(timeout) and exit(no_workers), or at least `exit(killed, {gen_server, call, [Worker, Call, Timeout]})` as with other exit reasons.

My research on the issue showed that the killed worker is registered at `monitor_worker/3` as `wpool_pool-<name>-1` but when it is killed the reveived message on the `wpool_queue_manager` is:
```erlang
{'DOWN', Ref, {'wpool_pool-<name>-1', Node}, killed}
```

As can be seen, the reveived message includes the node name. So the client is not being sent the message:

```erlang
{'EXIT', Worker, Reason}
```
as expected.

I fixed it for me with the following patch:
```diff
diff --git a/src/wpool_queue_manager.erl b/src/wpool_queue_manager.erl
index 201a86f..a48f157 100644
--- a/src/wpool_queue_manager.erl
+++ b/src/wpool_queue_manager.erl
@@ -245,6 +245,8 @@ handle_call(worker_counts, _From, State) ->

 %% @private
 -spec handle_info(any(), state()) -> {noreply, state()}.
+handle_info({'DOWN', Ref, Type, {Worker, _Node}, Exit}, State) ->
+    handle_info({'DOWN', Ref, Type, Worker, Exit}, State);
 handle_info({'DOWN', _, _, Worker, Exit}, State = #state{monitors = Mons}) ->
   case gb_trees:is_defined(Worker, Mons) of
     true ->
```
I tried to be the less intrusive as possible and I took in account the `monitors` field spec, which is `gb_trees:tree(atom(), monitored_from())`

Is this a good approach to solve the issue?

FYI: On my use case there is a single erlang node started with `-name <name>`.

**Comment by elbrujohalcon** [comment]
I think this is the proper approach to fix the issue indeed since `wpool` is not (and will probably never be) intended to run in more than one node.
I would certainly accept a PR with that change.

**Comment by elbrujohalcon** [comment]
@carlosvarelap you actually found something worth elevating to the @erlang team, considering [their docs](http://erlang.org/doc/reference_manual/processes.html#monitors) do not in any case indicate that `'DOWN'` messages can contain such a structure there.

**Comment by carlosvarelap** [comment]
In fact they have it documented:  http://erlang.org/doc/man/erlang.html#monitor-2
```
Object
The monitored entity, which triggered the event. When monitoring a local process or port,
Object will be equal to the pid() or port() that was being monitored. When monitoring
process or port by name, Object will have format {RegisteredName, Node} where
 RegisteredName is the name which has been used with monitor/2 call and Node is
local or remote node name (for ports monitored by name, Node is always local node name).
```

**Comment by elbrujohalcon** [comment]
Yeah… I was just about to write that it was documented… but somewhere else 🙄
