### ISSUE TITLE
Integration with code coverage service

### ISSUE THREAD

**Issue by michalwski** [inaka/worker_pool#154]
It'd good to show in an easy way the coverage of the project which is at amazing level of 95%. There are service like:
* https://coveralls.io/
* or https://codecov.io/

which could be used to visualize the coverage.

We have them both integrated in [esl/exml](https://github.com/esl/exml) and [esl/MongooseIM](https://github.com/esl/MongooseIM)

The integration may be as simple as (in rebar.config):

```erlang
{plugins                , [coveralls,
                           {rebar3_codecov,
                            {git, "https://github.com/zofpolkowska/rebar3_codecov.git",
                             {ref, "3d0af19"}}}
                          ]}.

{cover_enabled          , true}.
{cover_export_enabled   , true}.
{coveralls_coverdata    , "_build/test/cover/eunit.coverdata"}.
{coveralls_service_name , "travis-ci"}.
```

Firstly, though, this repo needs to be added to one or both of the services.

**Comment by elbrujohalcon** [comment]
Yeah… In the past @ferigis applied some integrations to some other @inaka repos. I'll assign this ticket to him.
