### ISSUE TITLE
Delayed worker restarts

### ISSUE THREAD

**Issue by michalwski** [inaka/worker_pool#158]
We are thinking about adding to worker_pool ability to restart workers with a delay. Would you accept such a PR? Also if yes would it be OK to use [supervisor2](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/supervisor2.erl) from RabbitMQ for that?

**Comment by elbrujohalcon** [comment]
A few questions:
1. Can the delay be somehow embedded in the worker `init/1` functions?
2. Do we really need wpool to take care of that delay instead of letting the workers do it on their own?
3. If we really need to add this functionality to wpool itself, why adding `supervisor2` instead of just adding some delay to `wpool_process`?

**Comment by michalwski** [comment]
I'm answering to question number 2 as this is the most important. There are 2 reasons behind this:

1. In order prevent the whole Erlang node crash if a connection pool to a DB was lost. We'd rather want to keep trying to reconnect (with some delay).
2. To have control over the restarts in one place (worker_pool) instead of all the 3rd party libs.

@fenek please add your thoughts to this discussion as well.

**Comment by elbrujohalcon** [comment]
OK, folks… I don't mind adding this functionality but I wouldn't do it with `supervisor2` unless it's 100% necessary.

**Comment by michalwski** [comment]
I wonder how this logic could be added `wpool_process` in current architecture where it's a wrapper around the real worker. The only way which comes to my mind at this moment is to always use:
```erlang
process_flag(trap_exit, true)
```

so the `terminate` function is always called and we can introduce the delay in this functions. This doesn't smell well to me.

Alternatively we could change the architecture so that the `wpool_process` (if set to manage restarts) is not a wrapper but a separate process which `spawn_links` the real worker process and:
* forwards every `call`, `cast`, `info` to the other process
* manages restarts of the real process.

This doesn't smell that bad, on the other hand it doubles number of process for a pool and number of messages sent which may impact performance.

I hope I missed sth, and you (@fenek, @elbrujohalcon) can enlighten me.

**Comment by elbrujohalcon** [comment]
@michalwski I was just thinking in adding a `timer:sleep/1` call in `wpool_process:init/1`, _before_ calling `Mod:init/1` [here](https://github.com/inaka/worker_pool/blob/df2769c1872989f2fa456b337417d3d909150fc0/src/wpool_process.erl#L83).

Was I too naïve?

**Comment by fenek** [comment]
If the delay reaches e.g. seconds or tens of seconds, such worker could be flooded with requests to process (while still in `init`), with certain selection strategies.

Maybe workers should be created with restart mode set to `temporary` and we would create a dedicated process (a sibling of `wpool_process_sup`) responsible for adding worker children to the supervisor and taking actions when they terminate?

**Comment by elbrujohalcon** [comment]
But is it reasonable for a delay to reach seconds or tens of seconds?
I think there are strategies (I should check which ones) that rely on workers being up _all the time_ (i.e. they find them by name and they build the name dynamically). For those strategies, we probably can't just keep the worker down for long periods of time.
On the other hand, when does OTP register the process… before or after `init/1` is done? If it's _after_, then the process will not be flooded with messages, right? It won't… _exist_ in a sense.

**Comment by michalwski** [comment]
The registration is one of the first operations of a process (when started via `gen_*:start[_link]`). So the name is available before the gen_server does its `init` function.
The more I'm thinking how to implement this, the more I think it doesn't fit into `worker_pool`.

@fenek we need this functionality in MongooseIM so how about implementing the delayed restart in MongooseIM when we detect that the entire pool crashed? It would mean that the whole pool is restarted with a delay, not a single worker.

**Comment by elbrujohalcon** [comment]
I'm with you on this one, @michalslaski … I think wpool is not ready for such a feature.

**Comment by fenek** [comment]
OK, very well, maybe it's a better approach indeed. After all, usually when a database is unavailable, it is so for all workers, not just some of them. :) I agree.
