### ISSUE TITLE
3.2.0 Release

### ISSUE THREAD

**Issue by michalwski** [inaka/worker_pool#159]
Or 3.1.2. @elbrujohalcon what needs to be done in order to create new release from the `rel-3.1` branch?

**Comment by elbrujohalcon** [comment]
Not much, I can do it.
Do you want it on hex, as well?

**Comment by elbrujohalcon** [comment]
@michalwski it's here: https://github.com/inaka/worker_pool/releases/tag/3.2.0
And here: https://hex.pm/packages/worker_pool/3.2.0

**Comment by michalwski** [comment]
Thanks a lot!
