### ISSUE TITLE
ability to provide custom strategies

### ISSUE THREAD

**Issue by marianoguerra** [inaka/worker_pool#16]
I need something almost exactly like this but with a different strategy that needs code from another project.

I need a strategy to pick a worker consistently given a key, for this I can use the chash module from riak_core https://github.com/basho/riak_core/blob/develop/src/chash.erl

by creating a ring of the same size as the worker_pool size I can consistently get the same worker given the same key (many keys will match the same worker).

for this I need two things:

1. ability to register or provide a strategy at some point in the pool initialization
2. ability to provide parameters to the strategy each time I ask for a worker

I will try to provide an initial pull request for this in the following days if I manage to get around the code.

**Comment by marianoguerra** [comment]
I was looking around the code and here are some things I thought.

a new strategy called custom that receives Sup and Call parameters (as far as I understand Call are the parameters that will be sent to the worker) it will try to get the WPool and call the fun(Sup, Call, Wpoll) configured in wpoll:option() called strategy_handler.

the strategy_handler must return a worker.

now, in my case I need some way to go through the workers and information about them (in my case I would have a mapping of PartitionId -> Worker that I would use to return the correct worker.

from what I've seen I could have this information in wpool_queue_manager or have some way to be notified on worker creation and get the pid so I can keep the mapping on my side (not sure this would be something nice).

my custom strategy would calculate the PartitionId from the Call parameter and get the worker from the PartitionId -> Worker mapping and return it.

let me know what you think.

**Comment by marianoguerra** [comment]
here is a simple change with some of the parts, the missing thing is the information store about the worker and maybe an api the custom strategy can use to have access to all the info it may need to make the decision:

https://github.com/marianoguerra/worker_pool/compare/issue_16_custom_strategies

**Comment by elbrujohalcon** [comment]
@marianoguerra it's looking good, thanks! Three small comments:

- The wpool() type is `pid() | atom()`
- Please use [2 spaces](https://github.com/inaka/erlang_guidelines#spaces-over-tabs) for indentation, at least to [follow the style](https://github.com/inaka/erlang_guidelines#maintain-existing-style) in the rest of the project ;)
- Please add some tests

**Comment by elbrujohalcon** [comment]
I believe this is fixed with #52. What do you think, @marianoguerra ?
