### ISSUE TITLE
add optional worker callbacks

### ISSUE THREAD

**Issue by benoitc** [inaka/worker_pool#166]
Starting in erlang 20, a gen_server has optional callbacks like `handle_info`, `terminate` and `code_change`. But the current worker behaviour enforce them. IMO we should expect the worker API to be similar to a `gen_server`. Thoughts?

**Comment by elbrujohalcon** [comment]
You're entirely correct. Optional `gen_server` callbacks should also be optional for `wpool`.

**Comment by elbrujohalcon** [comment]
Fixed by #206
