### ISSUE TITLE
Release 4.1.0

### ISSUE THREAD

**Issue by michalwski** [inaka/worker_pool#168]
I can see there is milestone 4.1.0 created with 3 open issues. Are these issues mandatory before releasing 4.1.0? I'm interested in a new release because in esl/MongooseIM#2513 we want to upgrade from `worker_pool` 3.x to 4.x but version 4.0.0 doesn't contain required changes which are already in master branch.

**Comment by elbrujohalcon** [comment]
Yeah, I do want to get those in for 4.1.0… but… I can release 4.0.1 first.

**Comment by elbrujohalcon** [comment]
There you go: https://github.com/inaka/worker_pool/releases/tag/4.0.1
And: https://hex.pm/packages/worker_pool

**Comment by michalwski** [comment]
Thanks a lot @elbrujohalcon!
