### ISSUE TITLE
Killing 'wpool_pool' supervisor kills the entire application

### ISSUE THREAD

**Issue by tlarevo** [inaka/worker_pool#185]
I'm trying to implement worker_pool with elixir application. I observed that when you kill the 'wpool_pool' supervisor that under another supervisor it crashes the entire application. This is same for when the 'wpool_pool' under its own supervisor, it brings down the entire application. Is this the intended behaviour? I would prefer that higher level supervisor could restart the 'wpool_pool'. Pardon me for my lack of knowledge in this domain. What am I missing here?

**Comment by elbrujohalcon** [comment]
Let me see if I understood correctly… 
You're starting  a pool with `wpool:start_pool/1,2` or `wpool:start_sup_pool/1,2`, then killing it with `wpool:stop_pool/1` and then the whole `worker_pool` application is terminated?

If that's so, then that's a bug… but I'll take a wild guess here and think that you're not doing just that.

Can you describe your scenario in more detail? Maybe show a minimal sample of what you're doing?

**Comment by tlarevo** [comment]
Please find the sample in this GitHub project [Test Wpool](https://github.com/tlarevo/test_wpool.git). I noticed that when create the worker pool with `wpool:stop_pool/1,2` or `wpool:start_sup_pool/1,2` it doesn't kill the entire application. However, if I start it with normal supervision tree approach, when killed, it kills the entire application.

**Comment by elbrujohalcon** [comment]
First of all… you can always try replacing [this](https://github.com/tlarevo/test_wpool/blob/833e832b566a984001bbc2e666fb3cfd141a5bce/lib/test_wpool/supervisor.ex#L27) with…

```erlang
        start: {:wpool, :start_pool, [:err_pool, [{:worker, {TestWpool.Worker, []}}, {:workers, 1}, {:queue_type, :lifo}, {:pool_sup_shutdown, :infinity}]]},
```

But I'm pretty sure that won't fix the issue.

Do you happen to have any logs of how the application dies? Maybe some SASL logs?

**Comment by tlarevo** [comment]
Actually, 

` start: {:wpool, :start_pool, [:err_pool, [{:worker, {TestWpool.Worker, []}}, {:workers, 1}, {:queue_type, :lifo}, {:pool_sup_shutdown, :infinity}]]},`

this is what I tried initially but it didn't work, so I tried with the `start_link` and it worked and I was able to get the `worker_pool` started but, when I killed it to test the supervisor functionality, It didn't work.

Furthermore, I found that if you use elixir `DynamicSupervisor` (I believe it's analogous to Supervisor with strategy `simple_one_to_one` in Erlang) to supervise the pool and then it doesn't bring down the entire application when the pool is killed.

As you requested I have attached, SASL logs. Let me know if I need to make any config changes to improve the logs.

[info.log](https://github.com/inaka/worker_pool/files/7764215/info.log)

**Comment by tlarevo** [comment]
@elbrujohalcon  I think, I found the issue. It seems that when the `wpool-pool` is killed `pool-process-sup` supervisor does not get killed immediately and keeps hanging and higher level supervisor tries to restart but fail even after multiple attempts and crashes. Tweaking the `max_restarts`, `max_seconds` in supervisor strategy enables `pool-process-sup` to shutdown and pool to restart properly.

I'll try to investigate why `pool-process-sup` keeps hanging when killed, let me know if you have a clue what I need to do differently.

**Comment by elbrujohalcon** [comment]
@tlarevo that seems very likely… considering that you're including `{:pool_sup_shutdown, :infinity}` in the worker pool options. That means that workers will have all the time in the world to terminate normally… If your supervisor has a smaller timeout (as [it does](https://github.com/tlarevo/test_wpool/blob/833e832b566a984001bbc2e666fb3cfd141a5bce/lib/test_wpool/supervisor.ex#L29): `5000`)… it will violently terminate before the worker pool sup and thus shutdown the whole thing.
Consider using `{:pool_sup_shutdown, 5000}` or even `{:pool_sup_shutdown, :brutal_kill}` in your pools.

**Comment by tlarevo** [comment]
@elbrujohalcon Thanks a lot. However, even with `brutal_kill` I had to start the supervisor with `max_restarts: 7, max_seconds: 5` to get the supervisor to restart the pool properly. Thanks again for your guidance and help 😃 💯
