### ISSUE TITLE
Name limited to local, couldn't it be open?

### ISSUE THREAD

**Issue by manuel-kaleyra** [inaka/worker_pool#197]
https://github.com/inaka/worker_pool/blob/366a9378b67535a187c013a0622b0eac5a402140/src/wpool_pool.erl#L54

I found that if I want to use gproc, syn or even configure global names, I cannot, it's limited to use `{local, Name}`. Could it be changed to use it only if the `Name` is an atom and in case it's a tuple, then use it as is? only to give us the possibility to use `{global, Name}` or `{via, ...}`.

**Comment by elbrujohalcon** [comment]
Yeah, good call. October is coming… so… maybe time for a nice pull request to get some #hacktoberfest points? 🙄

**Comment by elbrujohalcon** [comment]
No, my friend… only do it if *you* want it ;)

**Comment by elbrujohalcon** [comment]
Yeah… I believe that's exactly why we decided not to pursue this goal. It's not a non-desirable feature… it's just a really really complex one to implement.
