### ISSUE TITLE
Recover coverage upload to codecov

### ISSUE THREAD

**Issue by NelsonVides** [inaka/worker_pool#210]
As raised at https://github.com/inaka/worker_pool/pull/208#issuecomment-2365048825, codecov uploads are not working, we need to [update codecov action version to v4](https://github.com/inaka/worker_pool/blob/cd2e97f12fc61a74a479ec2b2461bfbe3d886cbe/.github/workflows/erlang.yml#L42), configure a token in codecov, and add the token to the github actions secrets.

See https://github.com/codecov/codecov-action?tab=readme-ov-file#usage for details.

**Comment by elbrujohalcon** [comment]
I was not aware that codecov is a paid service. I'll just remove it from our code.
