### ISSUE TITLE
R18 deprecation warning

### ISSUE THREAD

**Issue by ingwinlu** [inaka/worker_pool#25]
src/wpool_pool.erl:72: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.

**Comment by elbrujohalcon** [comment]
I would recommend switching to `ktn_random`, from [erlang-katana](http://github.com/inaka/erlang-katana)

**Comment by elbrujohalcon** [comment]
Fixed by #26
