### ISSUE TITLE
Possibility to create anonymous pools?

### ISSUE THREAD

**Issue by MAnyKey** [inaka/worker_pool#32]
AFAICS, there is no possibility to start pool without assigning name to it, both in terms of providing name to `wpool:start_pool/2` and using wpool:name() as first argument to `wpool:cast` and `wpool:call`

Is it possible to add such functionality?

**Comment by elbrujohalcon** [comment]
@MAnyKey the question is then: how will you use it? You can't just provide a pid to `wpool:call` because you don't really know which worker will process your call

**Comment by MAnyKey** [comment]
I thought about my request and realized that named pools will suite me. So, never mind.
Just to be clear: I am a bit nervous about assigning names to processes because (imo) it smells like a singleton.
