### ISSUE TITLE
wpool_queue_manager may leak workers

### ISSUE THREAD

**Issue by marcsugiyama** [inaka/worker_pool#37]
Assigning a job to a worker for the 'available_worker' strategy is a two step process. `wpool` first calls `wpool_pool:available_worker`, which in turn calls `wpool_queue_manager:available_worker`, which does a `gen_server:call` to the `wpool_queue_manager` process. This allocates the worker and the worker is marked as *busy* by `wpool_queue_manager`. The worker is returned to `wpool` which then calls `wpool_process` to assign the job to the worker. When the worker is done with the job, it informs `wpool_queue_manager` that it is available.

There is a window where the `gen_server:call` that allocates the worker times out but the worker is marked as allocated by `wpool_queue_manager`. Should this happen, work is never assigned to the worker so it never informs `wpool_queue_manager` that it is free. The worker is then lost from the pool.

Suggestion - Make the worker allocation and assignment of work an atomic operation to avoid this race condition.

**Comment by elbrujohalcon** [comment]
closed by #42
