### ISSUE TITLE
pool becomes unresponsive

### ISSUE THREAD

**Issue by JoshRagem** [inaka/worker_pool#81]
wpool 2.0.1

a simple hash worker cast:

```
wpool:cast(PoolName, {data, Metrics, UserId}, {hash_worker, UserId})
```

is failing silently. the workers are not busy because we can still send messages directly to them, but the pool is just doing nothing.

**Comment by elbrujohalcon** [comment]
@JoshRagem out of pure curiosity: what happened?

**Comment by JoshRagem** [comment]
I don't know, but I realized that I'm not matching against the return value, so I can't say it is failing silently.
