### ISSUE TITLE
wpool fails to handle temporarily dead workers

### ISSUE THREAD

**Issue by ElectronicRU** [inaka/worker_pool#94]
In particular, the following code:
```erlang
  case erlang:process_info(erlang:whereis(Worker), message_queue_len) of
    {message_queue_len, 0} -> Worker;
    {message_queue_len, L} ->
      min_message_queue(Checked + 1, next_wpool(Wpool), [{L, Worker} | Found])
  end.
```
in wpool_pool.erl fails if the worker is restarting, whether for valid or invalid reasons.

The dead workers aren't handled in any strategy, though; they're just assumed to be always alive. That's a shame since {stop, ...} tuples appear to be handled on the surface.

**Comment by elbrujohalcon** [comment]
Fair point. wpool should deal with `unefined` being the result of `erlang:whereis/1`. Thanks for spotting this, @ElectronicRU :)

**Comment by ElectronicRU** [comment]
https://github.com/inaka/worker_pool/blob/master/src/wpool_pool.erl#L223
this is another potentially problematic place
